# Generated by Django 5.1.7 on 2025-03-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_upload", "0002_extractedtext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("skills", models.TextField(blank=True, null=True)),
                ("education", models.TextField(blank=True, null=True)),
                ("experience", models.TextField(blank=True, null=True)),
                ("total_experience", models.FloatField(blank=True, null=True)),
                ("gaps", models.TextField(blank=True, null=True)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ExtractedText",
        ),
        migrations.DeleteModel(
            name="PDFDocument",
        ),
    ]
